import fontkit from '@pdf-lib/fontkit';
import { PDFDocument, rgb, type PDFFont, type PDFPage, type RGB } from 'pdf-lib';
import subsetFont from 'subset-font';
import { formatRM, formatYmd, formatYmdHms, isDraftRefNo, type ClaimDoc } from '@jep/shared';
import type { PdfAssets } from '../assets';
import { wrapText } from './wrapText';

export const COMPANY = {
  name: 'JEP VENTURES SDN BHD (1521088-K)',
  address:
    'D-2-15, Pusat Komersial Jalan Kuching, No. 115, Jalan Kepayang, Off Jalan Kuching, 51200 Kuala Lumpur, W.P. Kuala Lumpur',
};

export interface ClaimPdfInput {
  refNo: string;
  isDraft: boolean;
  applicant: { name: string; position: string };
  date: string;
  items: { description: string; amountCents: number; reference?: string }[];
  totalCents: number;
  payment: { bankName: string; accountHolder: string; accountNumber: string };
  approval: { byName: string; date: string } | null;
  generatedAt: string;
}

export interface PdfAttachment {
  mimeType: string;
  data: Uint8Array;
}

const A4: [number, number] = [595.28, 841.89];
const M = 40;
const FOOTER_SPACE = 36;
const DARK = rgb(0.1, 0.1, 0.1);
const GRAY = rgb(0.4, 0.4, 0.4);
const LINE = rgb(0.8, 0.8, 0.8);
const BAND = rgb(0.93, 0.93, 0.93);
const RED = rgb(0.75, 0.1, 0.1);
const DRAFT_MARK = 'DRAFT – PENDING APPROVAL';
const STATIC_TEXT = [
  'PAYMENT REQUEST', 'REF: ', DRAFT_MARK, 'APPLICANT DETAILS', 'Name', 'Position', 'Date',
  'CLAIM BREAKDOWN', 'No.', 'Doc No.', 'Description / Purpose', 'Amount (RM)', 'TOTAL', 'PAYMENT METHOD',
  'Recipient Bank', 'Account Holder', 'Account Number', 'APPROVAL', 'Approved by', 'Approved on',
  'Generated by JEP Ventures Claim System on ', 'This is a computer-generated document and no signature is required.',
  '0123456789 RM,.-:',
].join('');

async function embedFonts(doc: PDFDocument, fontBytes: Uint8Array, text: string) {
  doc.registerFontkit(fontkit);
  const src = Buffer.from(fontBytes);
  // keepFeatures: [] drops all GSUB/GPOS layout features. Without this, fontkit's
  // shaper (used by pdf-lib to encode drawn text) substitutes digits with glyphs
  // from a GSUB feature that this font keeps by default, while pdf-lib's ToUnicode
  // CMap is built from plain cmap lookups (no shaping) — the mismatch corrupts text
  // extraction (digits/some Latin punctuation decode as unrelated characters) even
  // though the glyphs render visually. CJK ideographs are unaffected either way.
  const [regular, bold] = await Promise.all(
    [400, 700].map((wght) =>
      subsetFont(src, text, { targetFormat: 'truetype', variationAxes: { wght }, keepFeatures: [] }),
    ),
  );
  return {
    regular: await doc.embedFont(regular!, { subset: false }),
    bold: await doc.embedFont(bold!, { subset: false }),
  };
}

export async function buildClaimPdf(
  input: ClaimPdfInput,
  attachments: PdfAttachment[],
  assets: PdfAssets,
): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  doc.setTitle(`Payment Request ${input.refNo}`);
  doc.setCreator('JEP Ventures Claim System');
  doc.setProducer('JEP Ventures Claim System');

  const { regular, bold } = await embedFonts(
    doc,
    assets.fontBytes,
    [COMPANY.name, COMPANY.address, STATIC_TEXT, JSON.stringify(input)].join(''),
  );
  const logo = await doc.embedPng(assets.logoPng);
  const [W, H] = A4;
  const contentW = W - 2 * M;
  const formPages: PDFPage[] = [];
  let page!: PDFPage;
  let y = 0;

  const newPage = () => {
    page = doc.addPage(A4);
    formPages.push(page);
    y = H - M;
  };
  const ensure = (h: number) => {
    if (y - h < M + FOOTER_SPACE) newPage();
  };
  const text = (s: string, x: number, size: number, font: PDFFont = regular, color: RGB = DARK, at = y) =>
    page.drawText(s, { x, y: at, size, font, color });
  const rightText = (s: string, right: number, size: number, font: PDFFont = regular) =>
    text(s, right - font.widthOfTextAtSize(s, size), size, font);
  const centered = (s: string, size: number, font: PDFFont, color: RGB = DARK) =>
    text(s, (W - font.widthOfTextAtSize(s, size)) / 2, size, font, color);

  newPage();

  // Letterhead
  const logoH = 48;
  const logoW = logo.width * (logoH / logo.height);
  page.drawImage(logo, { x: M, y: y - logoH, width: logoW, height: logoH });
  const headX = M + logoW + 14;
  let headY = y - 14;
  text(COMPANY.name, headX, 12, bold, DARK, headY);
  for (const line of wrapText(COMPANY.address, regular, 8.5, W - M - headX)) {
    headY -= 12;
    text(line, headX, 8.5, regular, GRAY, headY);
  }
  y = Math.min(y - logoH, headY) - 12;
  page.drawLine({ start: { x: M, y }, end: { x: W - M, y }, thickness: 1, color: DARK });
  y -= 30;

  // Title
  centered('PAYMENT REQUEST', 18, bold);
  y -= 18;
  centered(`REF: ${input.refNo}`, 10, regular, GRAY);
  y -= 14;
  if (input.isDraft) {
    centered(DRAFT_MARK, 10, bold, RED);
    y -= 14;
  }
  y -= 10;

  const section = (title: string) => {
    ensure(40);
    page.drawRectangle({ x: M, y: y - 5, width: contentW, height: 18, color: BAND });
    text(title, M + 6, 10, bold);
    y -= 24;
  };
  const field = (label: string, value: string) => {
    const lines = wrapText(value || '-', regular, 10, contentW - 130);
    ensure(lines.length * 14);
    text(label, M + 6, 10, regular, GRAY);
    lines.forEach((l, i) => text(l, M + 130, 10, regular, DARK, y - i * 14));
    y -= lines.length * 14 + 2;
  };

  section('APPLICANT DETAILS');
  field('Name', input.applicant.name);
  field('Position', input.applicant.position);
  field('Date', input.date);
  y -= 8;

  // Claim breakdown table
  section('CLAIM BREAKDOWN');
  const colNo = M + 6;
  const colDoc = M + 40;
  const docW = 90;
  const colDesc = colDoc + docW + 8;
  const colAmtRight = W - M - 6;
  const descW = colAmtRight - 100 - colDesc;
  const tableHeader = () => {
    text('No.', colNo, 9.5, bold);
    text('Doc No.', colDoc, 9.5, bold);
    text('Description / Purpose', colDesc, 9.5, bold);
    rightText('Amount (RM)', colAmtRight, 9.5, bold);
    y -= 6;
    page.drawLine({ start: { x: M, y }, end: { x: W - M, y }, thickness: 0.75, color: LINE });
    y -= 14;
  };
  tableHeader();
  input.items.forEach((item, i) => {
    const descLines = wrapText(item.description, regular, 10, descW);
    const docLines = wrapText(item.reference || '-', regular, 10, docW);
    const lines = descLines.length >= docLines.length ? descLines : docLines;
    if (y - (lines.length * 13 + 6) < M + FOOTER_SPACE) {
      newPage();
      tableHeader();
    }
    text(String(i + 1), colNo, 10);
    docLines.forEach((l, j) => text(l, colDoc, 10, regular, DARK, y - j * 13));
    descLines.forEach((l, j) => text(l, colDesc, 10, regular, DARK, y - j * 13));
    rightText(formatRM(item.amountCents).slice(3), colAmtRight, 10);
    const bottom = y - (lines.length - 1) * 13;
    page.drawLine({ start: { x: M, y: bottom - 6 }, end: { x: W - M, y: bottom - 6 }, thickness: 0.5, color: LINE });
    y = bottom - 20;
  });
  ensure(24);
  text('TOTAL', colDesc, 11, bold);
  rightText(formatRM(input.totalCents), colAmtRight, 11, bold);
  y -= 26;

  section('PAYMENT METHOD');
  field('Recipient Bank', input.payment.bankName);
  field('Account Holder', input.payment.accountHolder);
  field('Account Number', input.payment.accountNumber);

  if (input.approval) {
    y -= 8;
    section('APPROVAL');
    field('Approved by', input.approval.byName);
    field('Approved on', input.approval.date);
  }

  // Footer on every form page
  const footers: [string, number][] = [
    [`Generated by JEP Ventures Claim System on ${input.generatedAt}`, M + 10],
    ['This is a computer-generated document and no signature is required.', M],
  ];
  for (const p of formPages) {
    for (const [s, fy] of footers) {
      p.drawText(s, { x: (W - regular.widthOfTextAtSize(s, 7.5)) / 2, y: fy, size: 7.5, font: regular, color: GRAY });
    }
  }

  // Merged receipts
  for (const att of attachments) {
    if (att.mimeType === 'application/pdf') {
      const src = await PDFDocument.load(att.data, { ignoreEncryption: true });
      for (const p of await doc.copyPages(src, src.getPageIndices())) doc.addPage(p);
    } else {
      // Copy into a fresh, zero-offset Uint8Array: pdf-lib's JPEG embedder reads
      // `bytes.buffer` directly via DataView, and a Buffer from readFileSync can
      // point into Node's shared pool ArrayBuffer at a non-zero byteOffset, which
      // makes pdf-lib read from the wrong place and throw "SOI not found in JPEG".
      const data = new Uint8Array(att.data);
      const img = att.mimeType === 'image/png' ? await doc.embedPng(data) : await doc.embedJpg(data);
      const p = doc.addPage(A4);
      const scale = Math.min((W - 2 * M) / img.width, (H - 2 * M) / img.height, 1);
      const w = img.width * scale;
      const h = img.height * scale;
      p.drawImage(img, { x: (W - w) / 2, y: (H - h) / 2, width: w, height: h });
    }
  }

  return doc.save();
}

export function toPdfInput(c: ClaimDoc, now: Date): ClaimPdfInput {
  const isDraft = isDraftRefNo(c.refNo);
  return {
    refNo: c.refNo,
    isDraft,
    applicant: { name: c.applicant.name, position: c.applicant.position },
    date: formatYmd(c.submittedAt.toDate()),
    items: c.items.map((i) => ({ description: i.description, amountCents: i.amountCents, reference: i.reference })),
    totalCents: c.totalCents,
    payment: c.payment,
    approval: !isDraft && c.review ? { byName: c.review.byName, date: formatYmd(c.review.at.toDate()) } : null,
    generatedAt: formatYmdHms(now),
  };
}
